// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOIvB4EvQMVce6-f2HXZzPL6QkkD2pv5M',
    appId: '1:12417387484:web:3d7fcd8ab88ab62dcddd19',
    messagingSenderId: '12417387484',
    projectId: 'gayathri-514db',
    authDomain: 'gayathri-514db.firebaseapp.com',
    storageBucket: 'gayathri-514db.appspot.com',
    measurementId: 'G-23022JBBR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk_21Jx769eAjjaslFoAOr0ItpaAaDPNU',
    appId: '1:12417387484:android:45f598f64d703b88cddd19',
    messagingSenderId: '12417387484',
    projectId: 'gayathri-514db',
    storageBucket: 'gayathri-514db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCumzqkG_ssn370EM9MjnAcchChjacL5GU',
    appId: '1:12417387484:ios:e4782e9763e23976cddd19',
    messagingSenderId: '12417387484',
    projectId: 'gayathri-514db',
    storageBucket: 'gayathri-514db.appspot.com',
    iosBundleId: 'com.example.webpage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOIvB4EvQMVce6-f2HXZzPL6QkkD2pv5M',
    appId: '1:12417387484:web:f447f3f41e2ccce3cddd19',
    messagingSenderId: '12417387484',
    projectId: 'gayathri-514db',
    authDomain: 'gayathri-514db.firebaseapp.com',
    storageBucket: 'gayathri-514db.appspot.com',
    measurementId: 'G-ZXYXXDYKQV',
  );
}
